reporter: "xcode"
included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - ichime

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_collection_literal
  - empty_count
  - empty_string
  - modifier_order
  - sorted_enum_cases
  - sorted_imports


disabled_rules:
  - nesting
  - todo

identifier_name:
  min_length: 1
