name: Ichime
fileGroups:
- .editorconfig
- .gitignore
- .github/
- .swift-format
- .swiftformat
- .swiftlint.yml
- Makefile
- project.yml
- README.md
options:
  developmentLanguage: ru
  groupSortPosition: top
  indentWidth: 2
packages:
  Anime365ApiClient:
    path: ./Anime365ApiClient
  JikanApiClient:
    path: ./JikanApiClient
  ScraperAPI:
    path: ./ScraperAPI
  ShikimoriApiClient:
    path: ./ShikimoriApiClient
  DITranquillity:
    url: https://github.com/ivlevAstef/DITranquillity.git
    from: "4.5.0"
targets:
  Ichime:
    type: application
    platform: [tvOS]
    deploymentTarget:
      tvOS: "18.0"
    scheme:
      configVariants: # Костыль для того, чтобы в Xcode автоматически создавалась схема этого таргета
    sources:
      - path: Ichime
      - path: Settings.bundle # Явно добавляем папку Settings.bundle в билд таргета, чтобы наше приложение отобразилось в системных настройках
    entitlements:
      path: Ichime/Ichime.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group] # Application Groups нужны для расшаренных UserDefaults между основным приложением и Top Shelf
    dependencies:
      - package: DITranquillity
      - package: Anime365ApiClient
      - package: JikanApiClient
      - package: ScraperAPI
      - package: ShikimoriApiClient
      - target: TopShelf_tvOS
        destinationFilters: [tvOS]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES" # Так как мы свой Info.plist пока не используем, то просим Xcode генерировать Info.plist автоматически, а все параметры добавляем через INFOPLIST_KEY_*
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime # Bundle ID этого таргета
  TopShelf:
    type: app-extension
    platform: [tvOS]
    supportedDestinations: tvOS
    deploymentTarget:
      tvOS: "18.0"
    sources:
      - path: Ichime/Extensions/ScraperAPI.Types.Episode.swift
      - path: Ichime/DependencyInjection/ServiceLocator.swift
      - path: TopShelf
    info:
      path: TopShelf/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION) # Техническая версия приложения
        CFBundleShortVersionString: $(MARKETING_VERSION) # Человекочитабельная версия приложения
        NSExtension:
          NSExtensionPointIdentifier: com.apple.tv-top-shelf # Тип экстеншена - Top Shelf
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ContentProvider # Класс, являющийся точкой входа в экстеншен
    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group] # Application Groups нужны для расшаренных UserDefaults между основным приложением и Top Shelf
    dependencies:
      - package: Anime365ApiClient
      - package: ScraperAPI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime.TopShelf # Bundle ID этого таргета
settings:
  base:
    CURRENT_PROJECT_VERSION: 108000 # Техническая версия приложения
    DEVELOPMENT_TEAM: YBBAN7R28K # ID аккаунта команды Apple Developer
    INFOPLIST_KEY_CFBundleDisplayName: Ichime # Человекочитабельное название приложения. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the CFBundleDisplayName key in the Info.plist file to the value of this build setting.
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment # К какой категории относится приложение. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the LSApplicationCategoryType key in the Info.plist file to the value of this build setting.
    MARKETING_VERSION: "1.8.0" # Человекочитабельная версия приложения
    SWIFT_VERSION: "5" # Какую версию Swift использовать для компиляции приложения
  configs:
    Debug:
      INFOPLIST_KEY_CFBundleDisplayName: Ichime (dev) # Человекочитабельное название приложения. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the CFBundleDisplayName key in the Info.plist file to the value of this build setting.
