name: Ichime
fileGroups:
- .editorconfig
- .gitignore
- .github/
- .periphery.yml
- .swift-format
- .swiftformat
- .swiftlint.yml
- Makefile
- project.yml
- README.md
options:
  developmentLanguage: ru
  groupSortPosition: top
  indentWidth: 2
packages:
  Anime365Kit:
    path: ./Anime365Kit
  ThirdPartyVideoPlayer:
    path: ./ThirdPartyVideoPlayer
  JikanApiClient:
    path: ./JikanApiClient
  ShikimoriApiClient:
    path: ./ShikimoriApiClient
  Collections:
    url: https://github.com/apple/swift-collections.git
    from: "1.1.4"
  DITranquillity:
    url: https://github.com/ivlevAstef/DITranquillity.git
    from: "4.5.0"
targets:
  Ichime:
    type: application
    platform: [tvOS]
    deploymentTarget:
      tvOS: "26.0"
    scheme:
      configVariants: # Костыль для того, чтобы в Xcode автоматически создавалась схема этого таргета
    sources:
      - path: Ichime
      - path: Settings.bundle # Явно добавляем папку Settings.bundle в билд таргета, чтобы наше приложение отобразилось в системных настройках
    info:
      path: Ichime/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLSchemes:
            - ichime
        LSApplicationQueriesSchemes: # Нужно для проверок UIApplication.shared.canOpenURL() в коде
          - infuse
          - vlc-x-callback
        UIRequiredDeviceCapabilities: [arm64] # Требуется для публикации в TestFlight
    entitlements:
      path: Ichime/Ichime.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group] # Application Groups нужны для расшаренных UserDefaults между основным приложением и Top Shelf
    dependencies:
      - package: DITranquillity
      - package: Collections
      - package: Anime365Kit
      - package: ThirdPartyVideoPlayer
      - package: JikanApiClient
      - package: ShikimoriApiClient
      - target: TopShelf_tvOS
        destinationFilters: [tvOS]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES" # Так как мы свой Info.plist пока не используем, то просим Xcode генерировать Info.plist автоматически, а все параметры добавляем через INFOPLIST_KEY_*
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime # Bundle ID этого таргета
        ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: >
          "App Icon - Gawr Gura"
          "App Icon - Hentai 365"
      configs:
        Debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image (Debug)"
  TopShelf:
    type: app-extension
    platform: [tvOS]
    supportedDestinations: tvOS
    deploymentTarget:
      tvOS: "26.0"
    sources:
      - path: Ichime/Anime365/Anime365BaseURL.swift
      - path: Ichime/Anime365/Anime365KitFactory.swift
      - path: Ichime/DependencyInjection/ServiceLocator.swift
      - path: Ichime/CurrentlyWatching/Type/EpisodeFromCurrentlyWatchingList.swift
      - path: Ichime/CurrentlyWatching/CurrentlyWatchingService.swift
      - path: Ichime/Show/Type/ShowName.swift
      - path: Ichime/Calendar/ShowReleaseSchedule.swift
      - path: Ichime/Calendar/Model/ShowFromCalendarWithExactReleaseDate.swift
      - path: Ichime/Calendar/Model/ShowsFromCalendarGroupedByDate.swift
      - path: Ichime/Utils/DateUtils.swift
      - path: TopShelf
    info:
      path: TopShelf/Info.plist
      properties:
        CFBundleDisplayName: $(PRODUCT_NAME) TopShelf # Требуется для публикации в TestFlight
        CFBundleVersion: $(CURRENT_PROJECT_VERSION) # Техническая версия приложения
        CFBundleShortVersionString: $(MARKETING_VERSION) # Человекочитабельная версия приложения
        UIRequiredDeviceCapabilities: [arm64] # Требуется для публикации в TestFlight
        NSExtension:
          NSExtensionPointIdentifier: com.apple.tv-top-shelf # Тип экстеншена - Top Shelf
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ContentProvider # Класс, являющийся точкой входа в экстеншен
    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group] # Application Groups нужны для расшаренных UserDefaults между основным приложением и Top Shelf
    dependencies:
      - package: Collections
      - package: Anime365Kit
      - package: JikanApiClient
      - package: ShikimoriApiClient
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime.TopShelf # Bundle ID этого таргета
settings:
  base:
    CURRENT_PROJECT_VERSION: 101000 # Техническая версия приложения
    DEVELOPMENT_TEAM: YBBAN7R28K # ID аккаунта команды Apple Developer
    INFOPLIST_KEY_CFBundleDisplayName: Ichime # Человекочитабельное название приложения. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the CFBundleDisplayName key in the Info.plist file to the value of this build setting.
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment # К какой категории относится приложение. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the LSApplicationCategoryType key in the Info.plist file to the value of this build setting.
    MARKETING_VERSION: "1.10.0" # Человекочитабельная версия приложения
    SWIFT_VERSION: "6" # Какую версию Swift использовать для компиляции приложения

    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: "YES" # From "Update to recommended settings" prompt
    ENABLE_USER_SCRIPT_SANDBOXING: "YES" # From "Update to recommended settings" prompt
    LOCALIZATION_PREFERS_STRING_CATALOGS: "YES" # From "Update to recommended settings" prompt
  configs:
    Debug:
      INFOPLIST_KEY_CFBundleDisplayName: Ichime (dev) # Человекочитабельное название приложения. When GENERATE_INFOPLIST_FILE is enabled, sets the value of the CFBundleDisplayName key in the Info.plist file to the value of this build setting.
