name: Ichime
fileGroups:
- .editorconfig
- .gitignore
- .github/
- .swift-format
- Makefile
- project.yml
- README.md
options:
  developmentLanguage: ru
  groupSortPosition: top
  indentWidth: 2
packages:
  Anime365ApiClient:
    path: ./Anime365ApiClient
  ScraperAPI:
    path: ./ScraperAPI
  ShikimoriApiClient:
    path: ./ShikimoriApiClient
  DITranquillity:
    url: https://github.com/ivlevAstef/DITranquillity.git
    from: "4.5.0"
targets:
  Ichime:
    type: application
    platform: [tvOS]
    deploymentTarget:
      tvOS: "18.1"
    sources:
      - path: Ichime
    info:
      path: Ichime/Info.plist
      properties:
        BGTaskSchedulerPermittedIdentifiers: [dev.midorinome.ichime.background-tasks]
        CFBundleShortVersionString: $(APP_VERSION)
        CFBundleURLTypes:
          - CFBundleTypeRole: viewer
            CFBundleURLName: $(PRODUCT_BUNDLE_IDENTIFIER).TopShelfURL
            CFBundleURLSchemes: [ichime-top-shelf]
        CFBundleVersion: $(APP_VERSION)
        LSApplicationCategoryType: public.app-category.entertainment
        UIBackgroundModes:
          - audio
          - processing
          - fetch
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: Ichime/Ichime.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group]
    dependencies:
      - package: DITranquillity
      - package: Anime365ApiClient
      - package: ScraperAPI
      - package: ShikimoriApiClient
      - target: TopShelf_tvOS
        destinationFilters: [tvOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime
        MARKETING_VERSION: $(APP_VERSION)
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: YBBAN7R28K
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.entertainment
      configs:
        Release:
          DEBUG_MODE: NO
          PRODUCT_NAME: $(APP_NAME)
          INFOPLIST_KEY_CFBundleDisplayName: $(APP_NAME)
        Debug:
          DEBUG_MODE: YES
          PRODUCT_NAME: $(APP_NAME) (dev)
          INFOPLIST_KEY_CFBundleDisplayName: $(APP_NAME) (dev)
  TopShelf:
    type: app-extension
    platform: [tvOS]
    supportedDestinations: tvOS
    deploymentTarget:
      tvOS: "18.1"
    sources:
      - path: Ichime/Extensions/ScraperAPI.Types.Episode.swift
      - path: Ichime/DependencyInjection/ServiceLocator.swift
      - path: TopShelf
    info:
      path: TopShelf/Info.plist
      properties:
        CFBundleShortVersionString: $(APP_VERSION)
        CFBundleVersion: $(APP_VERSION)
        CFBundleDisplayName: TopShelf
        UIRequiredDeviceCapabilities:
          - arm64
        NSExtension:
          NSExtensionPointIdentifier: com.apple.tv-top-shelf
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ContentProvider
    entitlements:
      path: TopShelf/TopShelf.entitlements
      properties:
        com.apple.security.application-groups: [group.dev.midorinome.ichime.group]
    dependencies:
      - package: Anime365ApiClient
      - package: ScraperAPI
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.midorinome.ichime.TopShelf
        MARKETING_VERSION: $(APP_VERSION)
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: YBBAN7R28K
      configs:
        Release:
          DEBUG_MODE: NO
        Debug:
          DEBUG_MODE: YES

settings:
  SWIFT_VERSION: "5"
  APP_VERSION: "1.8.0"
  APP_NAME: Ichime
