name: Build

on:
  pull_request:
    paths:
      - project.yml

jobs:
  xcodegen:
    name: XcodeGen
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode configs
        run: xcodegen generate
