name: Code Quality

on: pull_request

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: swift format lint . --recursive --strict

  swiftformat:
    name: SwiftFormat
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: swiftformat --lint .

  swiftlint:
    name: SwiftLint
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Check Code Formatting
        run: swiftlint --strict
