name: Code Quality

on: pull_request

jobs:
  xcodegen:
    name: XcodeGen
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Configs
        run: xcodegen generate

      - name: Upload Ichime.xcodeproj Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ichime
          path: ./
          retention-days: 7
          include-hidden-files: true

  swift_format:
    name: swift-format
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: swift format lint . --recursive --strict

  swiftformat:
    name: SwiftFormat
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Code Formatting
        run: swiftformat --lint .

  swiftlint:
    name: SwiftLint
    runs-on: macos-15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Check Code Formatting
        run: swiftlint --strict

  periphery:
    name: Periphery
    runs-on: macos-15
    needs: [xcodegen]

    steps:
      - name: Download Repository w/ Xcode Configs Artifact
        uses: actions/download-artifact@v4
        with:
          name: ichime
          path: ./

      - name: Install Periphery
        run: brew install periphery

      - name: Check For Unused Code
        run: periphery scan

  xcodebuild:
    name: xcodebuild
    runs-on: macos-15
    needs: [xcodegen]

    steps:
      - name: Download Repository w/ Xcode Configs Artifact
        uses: actions/download-artifact@v4
        with:
          name: ichime
          path: ./

      - name: Resolve Dependencies
        run: xcodebuild -resolvePackageDependencies -scheme Ichime_tvOS

      - name: Archive with Xcodebuild
        run: xcodebuild -scheme Ichime_tvOS -configuration Release -archivePath ./build/ichime.xcarchive -sdk appletvos archive   CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

#      - name: Export Archive as IPA with xcodebuild
#        run: xcodebuild -exportArchive -archivePath ./build/ichime.xcarchive -exportOptionsPlist ./Ichime/ExportOptions.plist -exportPath ./build/ipa

      - name: Package .app into .ipa
        run: |
          mkdir -p Payload
          cp -R ./build/ichime.xcarchive/Products/Applications/Ichime.app Payload/
          zip -r Ichime.ipa Payload
          rm -rf Payload

      - name: Upload Unsigned IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ichime-ipa
          path: Ichime.ipa
